from __future__ import annotations

from bias_core.extensions import PermissionDefinition

from bias_ext_discussions.backend.constants import EXTENSION_ID


def permission_definitions():
    return (
        PermissionDefinition(
            code="viewForum",
            label="查看论坛",
            section="view",
            section_label="查看权限",
            module_id=EXTENSION_ID,
            icon="fas fa-eye",
            description="允许访问论坛讨论流和讨论详情。",
        ),
        PermissionDefinition(
            code="startDiscussion",
            label="发起讨论",
            section="start",
            section_label="发帖权限",
            module_id=EXTENSION_ID,
            icon="fas fa-edit",
            description="允许创建新讨论。",
        ),
        PermissionDefinition(
            code="startDiscussionWithoutApproval",
            label="发起讨论免审核",
            section="start",
            section_label="发帖权限",
            module_id=EXTENSION_ID,
            icon="fas fa-user-check",
            description="发起讨论后直接公开，无需进入审核队列。",
            required_permissions=("startDiscussion",),
        ),
        PermissionDefinition(
            code="discussion.reply",
            label="回复讨论",
            section="reply",
            section_label="回复权限",
            module_id=EXTENSION_ID,
            icon="fas fa-reply",
            description="允许在讨论中发布回复。",
            required_permissions=("viewForum",),
        ),
        PermissionDefinition(
            code="replyWithoutApproval",
            label="回复免审核",
            section="reply",
            section_label="回复权限",
            module_id=EXTENSION_ID,
            icon="fas fa-user-check",
            description="回复后直接公开，无需进入审核队列。",
            required_permissions=("discussion.reply",),
        ),
        PermissionDefinition(
            code="discussion.typing",
            label="发送输入提示",
            section="reply",
            section_label="回复权限",
            module_id=EXTENSION_ID,
            icon="fas fa-keyboard",
            description="允许在讨论实时流里向其他用户显示“正在输入”提示。",
            required_permissions=("discussion.reply",),
        ),
        PermissionDefinition(
            code="discussion.editOwn",
            label="编辑自己的帖子",
            section="reply",
            section_label="回复权限",
            module_id=EXTENSION_ID,
            icon="fas fa-pencil-alt",
            description="允许作者编辑自己的讨论首帖或回复。",
        ),
        PermissionDefinition(
            code="discussion.deleteOwn",
            label="删除自己的帖子",
            section="reply",
            section_label="回复权限",
            module_id=EXTENSION_ID,
            icon="fas fa-times",
            description="允许作者删除自己的讨论或回复。",
        ),
        PermissionDefinition(
            code="discussion.edit",
            label="编辑任意帖子",
            section="moderate",
            section_label="内容管理",
            module_id=EXTENSION_ID,
            icon="fas fa-pencil-alt",
            description="允许管理任意讨论首帖与回复。",
            required_permissions=("viewForum",),
        ),
        PermissionDefinition(
            code="discussion.delete",
            label="删除任意帖子",
            section="moderate",
            section_label="内容管理",
            module_id=EXTENSION_ID,
            icon="fas fa-trash",
            description="允许删除任意讨论或回复。",
            required_permissions=("discussion.hide",),
        ),
        PermissionDefinition(
            code="discussion.hide",
            label="隐藏内容",
            section="moderate",
            section_label="内容管理",
            module_id=EXTENSION_ID,
            icon="fas fa-eye-slash",
            description="允许隐藏或恢复讨论内容。",
            required_permissions=("viewForum",),
        ),
        PermissionDefinition(
            code="discussion.rename",
            label="重命名讨论",
            section="moderate",
            section_label="内容管理",
            module_id=EXTENSION_ID,
            icon="fas fa-heading",
            description="允许修改讨论标题。",
            required_permissions=("viewForum",),
        ),
        PermissionDefinition(
            code="discussion.lock",
            label="锁定讨论",
            section="moderate",
            section_label="内容管理",
            module_id=EXTENSION_ID,
            icon="fas fa-lock",
            description="允许锁定或解锁讨论。",
            required_permissions=("viewForum",),
        ),
        PermissionDefinition(
            code="discussion.sticky",
            label="置顶讨论",
            section="moderate",
            section_label="内容管理",
            module_id=EXTENSION_ID,
            icon="fas fa-thumbtack",
            description="允许置顶或取消置顶讨论。",
            required_permissions=("viewForum",),
        ),
    )
