# Generated by Django 5.0.3 on 2026-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0003_discussion_approval_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="discussion",
            name="discussions_user_id_4b0eee_idx",
        ),
        migrations.RemoveIndex(
            model_name="discussion",
            name="discussions_slug_00b0e3_idx",
        ),
        migrations.RemoveIndex(
            model_name="discussionuser",
            name="discussion__discuss_4635af_idx",
        ),
        migrations.RemoveIndex(
            model_name="discussionuser",
            name="discussion__user_id_f6be64_idx",
        ),
        migrations.AlterField(
            model_name="discussion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="last_posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
